prog:joueur.c perso.c source_background.c enemy.c collision.c minimap.c enigme2.c enigme_2.c enigme_1.c main_enigme.c 
	gcc joueur.c perso.c source_background.c enemy.c collision.c minimap.c enigme2.c enigme_2.c enigme_1.c main_enigme.c -o prog -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lm -g
